name: Push notification on the Blocksta repository

on: 
  push:
    branches: ['main']
  workflow_call:
    secrets:
      GOMU_CHANEL_ID:
        description: 'Specify the telegram channel id'
        required: true
      GOMU_BOT_TOKEN:
        description: 'Specify telegram bot token'
        required: true

jobs:
  notify:
    uses: GomuDevelopers/workflow_template/.github/workflows/notify_on_push.yaml@master
    secrets:
      GOMU_BOT_TOKEN: ${{ secrets.GOMU_BOT_TOKEN }}
      GOMU_CHANEL_ID: ${{ secrets.GOMU_CHANEL_ID }}

